env:
  browser: true
  commonjs: true
  es2021: true
extends:
  - airbnb-base
parserOptions:
  ecmaVersion: latest
ignorePatterns:
  - dist
rules:
  no-param-reassign: 0
  # object-curly-newline: 0
  implicit-arrow-linebreak: 0
